CREATE TRIGGER TEMPLATE_TABLE_TRG 
BEFORE INSERT ON TEMPLATE_TABLE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.COLUMN1 IS NULL THEN
      SELECT TEMPLATE_TABLE_SEQ.NEXTVAL INTO :NEW.COLUMN1 FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
